### ISSUE TITLE
Test Run Questions and Issues

### ISSUE THREAD

**Issue by EMCP** [JRGEMCP/MAHRIO-A#9]
This test run was with all code updated.. and broken down by user type

_Anon User_

* Title is mahrio/a , thinking it should be `Mahr.io Courses`?

Should the `Learn more` blue buttons goto the `tutorial` page, with the Collect, Transmit, etc. filter applied already? Same for the `view details` buttons

Talk to us should likely goto an email or webform

Register and Login modals
We need this eventually tested on HTTPS, enforce https only

need to add negative testing to the modals, including some scrubbing of inputs

_Authenticated User_

Once a user is logged in, clicking the main link should redirect to the dashboard instead of generic splash page

**Comment by JesusGuerrero** [comment]
Good comments!

**Comment by EMCP** [comment]
closing since Jesus changed the SPA setup and we need to review again from the beginning
